config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Open-EO/openeo-js-client:
      branch: master
      repo: https://github.com/Open-EO/openeo-js-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Open-EO/openeo-js-client git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-zucchini-raccoon.sh
        container: qc.acc_muzzy-salmon-whippet
  QC.Doc:
    repos:
      github.com/Open-EO/openeo-js-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-bistre-wolfhound.sh
        container: qc.doc_gimpy-ochre-lemming
      github.com/Open-EO/openeo-js-client git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-carmine-butterfly.sh
        container: qc.doc_freaky-teal-bonobo
      github.com/Open-EO/openeo-js-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-salmon-burmese.sh
        container: qc.doc_skimpy-khaki-centipede
  QC.Lic:
    repos:
      github.com/Open-EO/openeo-js-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-olivine-spitz.sh
        container: qc.lic_craggy-teal-dingo
  QC.Sty:
    repos:
      github.com/Open-EO/openeo-js-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-purple-frigatebird.sh
        container: qc.sty_snippy-linen-mule
  QC.Ver:
    repos:
      github.com/Open-EO/openeo-js-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cobalt-eel.sh
        container: qc.ver_pretty-auburn-scorpion
timeout: 5400
