config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Open-EO/openeo-js-client:
      branch: master
      repo: https://github.com/Open-EO/openeo-js-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Open-EO/openeo-js-client git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-russet-gorilla.sh
        container: qc.acc_hilly-burgundy-chin
  QC.Doc:
    repos:
      github.com/Open-EO/openeo-js-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-chartreuse-mouse.sh
        container: qc.doc_stealthy-brass-impala
      github.com/Open-EO/openeo-js-client git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-mauve-anteater.sh
        container: qc.doc_smelly-cerise-macaw
      github.com/Open-EO/openeo-js-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aqua-tortoise.sh
        container: qc.doc_chewy-coral-ostrich
  QC.Lic:
    repos:
      github.com/Open-EO/openeo-js-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-smalt-loon.sh
        container: qc.lic_shaky-khaki-vulture
  QC.Sty:
    repos:
      github.com/Open-EO/openeo-js-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-magnolia-mayfly.sh
        container: qc.sty_stealthy-tomato-dogfish
  QC.Ver:
    repos:
      github.com/Open-EO/openeo-js-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cyan-grasshopper.sh
        container: qc.ver_ugly-silver-woodlouse
timeout: 5400
